export const CHANGE_EMAIL_PENDING = "CHANGE_EMAIL_PENDING";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILED = "CHANGE_EMAIL_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORDCHECK = "CHANGE_PASSWORDCHECK";

export const CLICK_LOGIN_PENDING = "CLICK_LOGIN_PENDING";
export const CLICK_LOGIN_SUCCESS = "CLICK_LOGIN_SUCCESS";
export const CLICK_LOGIN_FAILED = "CLICK_LOGIN_FAILED";
export const CLICK_SIGNUP_PENDING = "CLICK_SIGNUP_PENDING";
export const CLICK_SIGNUP_SUCCESS = "CLICK_SIGNUP_SUCCESS";
export const CLICK_SIGNUP_FAILED = "CLICK_SIGNUP_FAILED";

export const REQUEST_RECOMMENDATIONS_BY_ID_PENDING = "REQUEST_RECOMMENDATIONS_BY_ID_PENDING";
export const REQUEST_RECOMMENDATIONS_BY_ID_SUCCESS = "REQUEST_RECOMMENDATIONS_BY_ID_SUCCESS";
export const REQUEST_RECOMMENDATIONS_BY_ID_FAILED = "REQUEST_RECOMMENDATIONS_BY_ID_FAILED";
