export const CHANGE_EMAIL_PENDING = "CHANGE_EMAIL_PENDING";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILED = "CHANGE_EMAIL_FAILED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORDCHECK = "CHANGE_PASSWORDCHECK";